#!/usr/bin/env bash

set -euo pipefail

export FLAGS=(
    "-fshort-enums"
    "-fsingle-precision-constant"
    "-march=native"
    "-O1"
    "-Wall"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat=2"
    "-Wformat-signedness"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)

now () {
    date +%s.%N
}

cppcheck \
    --enable=all \
    --suppress=missingIncludeSystem \
    "$WD/src" \
    | sed 's/\/.*\/\(.*\) \.\.\./\1/g'
clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
(
    start=$(now)
    gcc -g -o "$WD/bin/main" "${FLAGS[@]}" "$WD/src/main.c"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)
"$WD/bin/main" "$WD/out/Main.class"
printf "\n"
xxd "$WD/out/Main.class"
printf "\n"
javap -c -p -s -v "$WD/out/Main.class"
printf "\n"
java -cp .:"$WD/out" Main
