#!/usr/bin/env bash

set -euo pipefail

read -r -a flags <<< "$FLAGS"
wd="$WD/01_hello_world"

cppcheck \
    --enable=all \
    --suppress=missingIncludeSystem \
    "$wd/src" \
    | sed 's/\/.*\/\(.*\) \.\.\./\1/g'
clang-format -i -verbose "$wd/src"/* 2>&1 | sed 's/\/.*\///g'

start=$(now)
gcc -g -o "$wd/bin/main" "${flags[@]}" "$wd/src/main.c"
end=$(now)
python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"

"$wd/bin/main" "$wd/out/Main.class"
printf "\n"
xxd "$wd/out/Main.class"
printf "\n"
javap -c -p -s -v "$wd/out/Main.class"
printf "\n"
java -cp .:"$wd/out" Main
